default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  database: <%= ENV.fetch("PGDATABASE") { 'foun' } %>
  username: <%= ENV.fetch("PGUSER") { 'postgres' } %>
  password: <%= ENV.fetch("PGPASSWORD") { 'bluestaminauponreflection' } %>
  host: <%= ENV.fetch("PGHOST") { 'db' } %>

production:
  <<: *default

development:
  <<: *default
  database: foun

test:
  <<: *default
  database: foun_test