default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: postgres
  password: bluestaminauponreflection
  host: db

development:
  <<: *default
  database: foun

test:
  <<: *default
  database: foun_test