default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: postgres
  password: bluestaminauponreflection
  host: db

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE") %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  host: <%= ENV.fetch("PGHOST") %>

development:
  <<: *default
  database: foun

test:
  <<: *default
  database: foun_test